In [59]:
import pandas as pd 
import numpy as np 
from sklearn import linear_model 
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import *

In [66]:
df_price = pd.read_csv('data/price_availability.csv', sep=';')
df_listing = pd.read_csv('data/listings_final.csv', sep=';')
print('data loaded')

data loaded

In [69]:
df_price

,listing_id,day,created,available,local_currency,local_price,min_nights
0,9810829,2018-12-08,2018-09-27 06:14:10.000+0000,True,EUR,160,1
1,9810829,2018-12-08,2018-09-26 19:34:02.000+0000,True,EUR,160,1
2,20897010,2018-12-09,2018-09-27 10:38:57.000+0000,True,EUR,172,2
3,20897010,2018-12-09,2018-09-27 06:10:27.000+0000,True,EUR,172,2
4,20897010,2018-12-09,2018-09-26 19:30:25.000+0000,True,EUR,172,2
...,...,...,...,...,...,...,...
4748691,23608395,2018-09-06,2018-09-27 06:05:42.000+0000,False,EUR,24,1
4748692,23608395,2018-09-06,2018-09-26 19:31:32.000+0000,False,EUR,24,1
4748693,1447132,2018-12-27,2018-09-27 10:46:16.000+0000,False,EUR,125,3
4748694,1447132,2018-12-27,2018-09-27 06:07:36.000+0000,False,EUR,125,3
4748695,1447132,2018-12-27,2018-09-26 19:37:40.000+0000,False,EUR,125,3

In [70]:
df_listing

,Unnamed: 0,listing_id,name,type,city,neighborhood,latitude,longitude,person_capacity,beds,bedrooms,bathrooms,is_rebookable,is_new_listing,is_fully_refundable,is_host_highly_rated,is_business_travel_ready,pricing_weekly_factor,pricing_monthly_factor
0,0,28581061,La maison Clery,private_room,Paris,2e arrondissement,48.869292,2.348335,1,1,1,2.0,False,True,True,False,False,1.00,1.00
1,1,661961,studio PARIS PLACE EDITH PIAF 75020,entire_home,Paris,NaN,48.867284,2.403255,2,1,1,1.0,False,False,True,True,False,0.88,0.69
2,2,1261705,chambre privÃ©e Ã louer @ paris oberkampf,private_room,Paris,NaN,48.867894,2.375897,1,1,1,1.0,False,False,True,True,False,1.00,1.00
3,3,1318834,Appartement au coeur du Marais,entire_home,Paris,RÃ©publique,48.870370,2.358510,3,2,2,1.0,False,False,True,False,False,0.82,0.48
4,4,1677091,Lovely & Quiet flat,entire_home,Paris,Buttes-Chaumont - Belleville,48.874149,2.373700,2,1,1,1.0,False,False,True,True,False,0.95,0.90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,28335197,Studio cosy Jardin du Luxembourg,entire_home,Paris,Saint Germain des PrÃ©s - OdÃ©on,48.848695,2.325857,2,1,0,1.0,False,True,True,False,False,0.79,1.00
996,996,28583013,Charmant 30m2 - Faubourg Saint Martin,entire_home,Paris,RÃ©publique,48.871623,2.358006,3,1,1,1.0,False,True,True,False,False,1.00,1.00
997,997,28628316,Cosy flat in the marais - Best area,entire_home,Paris,2e arrondissement,48.867434,2.351771,4,2,1,1.0,False,True,True,True,False,1.00,1.00
998,998,28792796,Appartement 3 chambres madeleine.,entire_home,Paris,Madeleine - VendÃ´me,48.870109,2.321475,6,4,2,1.5,False,True,True,False,False,1.00,1.00
999,999,28682896,Village Jourdain,private_room,Paris,Buttes-Chaumont - Belleville,48.875425,2.395240,2,1,1,1.0,False,True,True,False,False,1.00,1.00

In [74]:
df_price = df_price.groupby(['listing_id']).mean()
df_listing = df_listing.groupby(['listing_id']).mean()
print("mean group by ok")

mean group by ok

In [75]:
df_price

            available  local_price  min_nights
listing_id
5396         0.011494   102.363985    2.000000
7397         0.168297   110.107632   11.000000
9342         0.309198   396.863014    2.784736
10010        0.254593   136.154856    4.955381
10270        0.511688   105.779221    4.937662
...               ...          ...         ...
28836096     0.082707   321.428571    1.022556
28838519     0.083333    54.483333    5.000000
28840013     0.743083   112.122530    2.000000
28846494     0.225564   168.037594    4.000000
28851976     0.812030   128.000000    2.000000

[11749 rows x 3 columns]

In [76]:
df_listing

,Unnamed: 0,latitude,longitude,person_capacity,beds,bedrooms,bathrooms,is_rebookable,is_new_listing,is_fully_refundable,is_host_highly_rated,is_business_travel_ready,pricing_weekly_factor,pricing_monthly_factor
listing_id,,,,,,,,,,,,,,
56093,12,48.867284,2.358431,4,2,1,1.0,False,False,True,True,False,0.88,1.0
57207,13,48.846184,2.304455,2,1,1,1.0,False,False,True,False,False,0.87,1.0
114543,19,48.849530,2.290219,2,1,1,1.0,False,False,True,True,False,0.90,0.9
149534,9,48.866360,2.361844,4,2,1,1.0,False,False,True,True,False,1.00,0.4
164255,28,48.861398,2.364299,4,2,1,1.0,False,False,True,False,False,1.00,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28684174,662,48.879223,2.292382,5,0,1,1.0,False,True,True,False,False,1.00,1.0
28709644,745,48.872202,2.298349,4,2,1,1.0,False,True,True,False,False,1.00,1.0
28751412,88,48.880923,2.314568,2,1,0,1.0,False,True,True,False,False,1.00,1.0
28774896,159,48.852915,2.314519,2,1,1,1.0,False,True,True,False,False,1.00,1.0
28792796,998,48.870109,2.321475,6,4,2,1.5,False,True,True,False,False,1.00,1.0

In [78]:
df_global = pd.merge(df_price[['local_price']], df_listing, on=['listing_id'])
df_global

,local_price,Unnamed: 0,latitude,longitude,person_capacity,beds,bedrooms,bathrooms,is_rebookable,is_new_listing,is_fully_refundable,is_host_highly_rated,is_business_travel_ready,pricing_weekly_factor,pricing_monthly_factor
listing_id,,,,,,,,,,,,,,,
56093,170.000000,12,48.867284,2.358431,4,2,1,1.0,False,False,True,True,False,0.88,1.0
57207,49.952756,13,48.846184,2.304455,2,1,1,1.0,False,False,True,False,False,0.87,1.0
114543,107.374026,19,48.849530,2.290219,2,1,1,1.0,False,False,True,True,False,0.90,0.9
149534,169.000000,9,48.866360,2.361844,4,2,1,1.0,False,False,True,True,False,1.00,0.4
164255,75.876209,28,48.861398,2.364299,4,2,1,1.0,False,False,True,False,False,1.00,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28684174,725.175781,662,48.879223,2.292382,5,0,1,1.0,False,True,True,False,False,1.00,1.0
28709644,475.000000,745,48.872202,2.298349,4,2,1,1.0,False,True,True,False,False,1.00,1.0
28751412,117.000000,88,48.880923,2.314568,2,1,0,1.0,False,True,True,False,False,1.00,1.0
28774896,156.397468,159,48.852915,2.314519,2,1,1,1.0,False,True,True,False,False,1.00,1.0
28792796,49.184211,998,48.870109,2.321475,6,4,2,1.5,False,True,True,False,False,1.00,1.0

In [84]:
y = df_global[["local_price"]]
x = df_global[["person_capacity","beds","bedrooms","bathrooms"]]

In [85]:
y = np.array(y)
x = np.array(x)

In [86]:
y

array([[ 170.        ],
       [  49.95275591],
       [ 107.37402597],
       [ 169.        ],
       [  75.8762089 ],
       [ 284.35356201],
       [  36.58961039],
       [ 300.        ],
       [ 101.37984496],
       [  67.20833333],
       [  60.74093264],
       [  38.        ],
       [  92.        ],
       [  66.21204188],
       [  79.68041237],
       [  90.09819121],
       [ 170.        ],
       [ 115.7544757 ],
       [ 283.76115486],
       [ 144.74424552],
       [ 347.67015707],
       [ 115.        ],
       [ 105.        ],
       [ 154.65384615],
       [ 380.        ],
       [  44.16569201],
       [ 233.69170984],
       [ 146.        ],
       [ 147.96623377],
       [ 105.        ],
       [ 163.47286822],
       [ 190.        ],
       [ 180.95287958],
       [ 128.8630491 ],
       [  44.47368421],
       [ 163.28571429],
       [  94.        ],
       [  94.97619048],
       [ 218.96373057],
       [ 234.89460154],
       [ 300.78640777],
       [  62.        ],
       [  59.02349869],
       [  80.24479167],
       [  53.        ],
       [  92.        ],
       [ 210.87855297],
       [ 278.90625   ],
       [ 165.        ],
       [ 179.67315175],
       [ 105.71849866],
       [  43.84615385],
       [ 105.15873016],
       [ 165.        ],
       [ 172.67822736],
       [ 109.        ],
       [  42.86340206],
       [ 220.        ],
       [ 136.57559682],
       [ 240.        ],
       [ 990.        ],
       [ 139.25876011],
       [ 196.03846154],
       [ 226.        ],
       [  69.        ],
       [ 357.44125326],
       [  62.3908046 ],
       [ 145.67829457],
       [ 191.34883721],
       [ 250.        ],
       [ 166.328125  ],
       [ 239.69726562],
       [ 199.42746114],
       [ 220.        ],
       [ 180.        ],
       [  59.07772021],
       [  61.10909091],
       [ 371.36363636],
       [  59.        ],
       [  58.        ],
       [ 315.48717949],
       [ 220.        ],
       [  86.        ],
       [ 132.18897638],
       [ 277.        ],
       [ 149.        ],
       [  69.01550388],
       [  49.        ],
       [ 245.        ],
       [ 161.2357513 ],
       [ 210.07792208],
       [ 216.22857143],
       [ 252.83854167],
       [  59.07731959],
       [  81.        ],
       [ 165.        ],
       [  60.65091864],
       [ 380.        ],
       [  73.        ],
       [  36.10742188],
       [ 180.        ],
       [ 184.55208333],
       [  92.28132992],
       [ 135.        ],
       [  74.        ],
       [ 210.        ],
       [  40.23498695],
       [ 258.2767624 ],
       [ 130.29320388],
       [  92.        ],
       [ 155.        ],
       [  29.        ],
       [ 122.58717949],
       [ 141.06994819],
       [ 228.44155844],
       [  69.77443609],
       [ 145.        ],
       [ 135.88020833],
       [  76.        ],
       [  98.        ],
       [ 144.        ],
       [ 184.65879265],
       [ 115.        ],
       [  35.06887755],
       [ 409.18085106],
       [  48.44041451],
       [  47.        ],
       [ 186.49807692],
       [ 220.03084833],
       [  80.56363636],
       [  89.25848564],
       [  79.        ],
       [ 183.9507772 ],
       [ 159.83507853],
       [  83.37730871],
       [ 195.26705653],
       [ 104.        ],
       [  43.58115183],
       [  45.82945736],
       [ 170.64935065],
       [ 158.86627907],
       [ 132.36363636],
       [ 202.23514212],
       [ 176.0839895 ],
       [  91.38659794],
       [ 109.        ],
       [ 261.08638743],
       [ 192.        ],
       [  96.05714286],
       [  74.        ],
       [  80.72440945],
       [ 170.        ],
       [ 440.        ],
       [ 321.2987013 ],
       [ 180.        ],
       [  68.16358839],
       [ 101.        ],
       [ 270.33678756],
       [  30.        ],
       [  76.06896552],
       [ 112.        ],
       [  57.        ],
       [ 435.12670565],
       [  88.19895288],
       [ 489.98035363],
       [  68.        ],
       [ 150.953125  ],
       [ 135.4015544 ],
       [ 108.        ],
       [ 591.40625   ],
       [  79.        ],
       [  25.44473008],
       [  51.72820513],
       [  48.39030612],
       [ 270.        ],
       [ 618.        ],
       [  30.        ],
       [ 395.        ],
       [  94.82597403],
       [ 133.8359375 ],
       [ 169.85714286],
       [ 250.        ],
       [ 108.        ],
       [ 118.19843342],
       [ 250.        ],
       [ 834.96124031],
       [  95.45333333],
       [ 206.14690722],
       [  88.65066667],
       [1072.77486911],
       [ 145.        ],
       [ 160.        ],
       [  63.14397906],
       [ 250.        ],
       [ 538.86010363],
       [ 140.16494845],
       [ 129.38481675],
       [ 144.        ],
       [ 425.        ],
       [  92.        ],
       [  54.        ],
       [ 127.        ],
       [  88.38381201],
       [  69.        ],
       [ 109.        ],
       [  72.        ],
       [  81.63049096],
       [ 148.07179487],
       [ 203.41755319],
       [  57.88653846],
       [ 136.62597403],
       [  69.27447217],
       [  74.10810811],
       [ 152.25773196],
       [  89.        ],
       [ 309.9034749 ],
       [  68.05526316],
       [ 350.08076923],
       [ 417.80392157],
       [ 212.13367609],
       [ 248.7244898 ],
       [  48.        ],
       [  39.        ],
       [ 119.        ],
       [ 350.        ],
       [  62.        ],
       [  96.6056701 ],
       [ 400.39787798],
       [ 176.29377432],
       [ 139.22779923],
       [ 349.79265092],
       [ 232.38921002],
       [  99.        ],
       [ 213.32460733],
       [  39.        ],
       [ 264.83558994],
       [ 159.        ],
       [ 403.08070866],
       [ 174.02849741],
       [ 290.        ],
       [ 296.        ],
       [ 115.        ],
       [  56.34645669],
       [ 239.53125   ],
       [  79.        ],
       [ 180.        ],
       [ 125.        ],
       [ 510.07751938],
       [ 260.94379845],
       [ 118.78473581],
       [ 327.96711799],
       [  29.        ],
       [ 160.        ],
       [ 160.        ],
       [  54.10433071],
       [  50.64107486],
       [  99.        ],
       [ 260.        ],
       [ 300.33419023],
       [  53.50129199],
       [ 195.72890026],
       [ 230.        ],
       [ 334.        ],
       [  44.66149871],
       [  42.        ],
       [ 181.04986877],
       [  88.98966408],
       [ 118.71465296],
       [  79.10344828],
       [  36.        ],
       [ 382.62135922],
       [  70.70103093],
       [  33.4296875 ],
       [  95.484375  ],
       [  42.        ],
       [ 311.54580153],
       [  51.82337662],
       [ 328.57699805],
       [ 105.        ],
       [ 130.13648294],
       [ 250.        ],
       [ 309.68911917],
       [  77.57772021],
       [ 105.        ],
       [ 196.98455598],
       [ 183.0848329 ],
       [ 149.        ],
       [  74.87743191],
       [ 215.9375    ],
       [  29.        ],
       [  52.        ],
       [ 189.12137203],
       [ 152.53299492],
       [  47.84473684],
       [ 718.09278351],
       [ 210.        ],
       [  98.        ],
       [ 148.        ],
       [ 195.        ],
       [ 163.60103627],
       [ 160.64136126],
       [  81.3110687 ],
       [ 415.98802395],
       [ 331.59615385],
       [  58.        ],
       [  33.53050398],
       [  20.        ],
       [ 459.71391076],
       [ 483.32432432],
       [ 297.76315789],
       [ 306.8477842 ],
       [1500.        ],
       [  98.35695538],
       [ 275.        ],
       [ 195.        ],
       [ 114.90421456],
       [ 277.78552972],
       [ 240.        ],
       [ 184.30628272],
       [ 220.        ],
       [ 168.2248062 ],
       [ 326.99232246],
       [  50.        ],
       [ 386.57751938],
       [  60.72307692],
       [  66.85299807],
       [ 115.        ],
       [ 203.89312977],
       [  49.60159363],
       [ 142.        ],
       [  32.86082474],
       [ 180.        ],
       [ 137.21204188],
       [ 520.61895551],
       [  21.        ],
       [ 115.52173913],
       [ 135.        ],
       [ 188.3203125 ],
       [  89.00773196],
       [ 494.36538462],
       [  81.66153846],
       [ 251.88824663],
       [ 238.25918762],
       [  58.        ],
       [  47.59585492],
       [ 240.37764933],
       [ 347.29166667],
       [ 145.        ],
       [  53.        ],
       [ 134.12532637],
       [  78.3685567 ],
       [ 794.54663212],
       [ 447.31538462],
       [  69.        ],
       [ 489.68911917],
       [  89.        ],
       [ 433.37958115],
       [  89.        ],
       [  30.        ],
       [ 255.87548638],
       [  51.52785146],
       [  97.18372703],
       [ 375.0268714 ],
       [  47.80577428],
       [ 278.95287958],
       [ 221.41015625],
       [  70.96899225],
       [  48.        ],
       [ 221.83333333],
       [  62.        ],
       [  75.79895561],
       [ 159.933687  ],
       [ 260.        ],
       [ 340.        ],
       [  84.63852243],
       [ 170.7310705 ],
       [  40.        ],
       [ 149.        ],
       [  86.        ],
       [ 237.48051948],
       [  79.        ],
       [ 161.59689922],
       [ 160.02645503],
       [ 517.99618321],
       [ 142.23958333],
       [ 143.        ],
       [  34.23136247],
       [ 117.38684211],
       [  35.11111111],
       [ 254.41005803],
       [ 156.14038462],
       [ 127.91237113],
       [ 322.24102564],
       [ 391.4452975 ],
       [ 330.        ],
       [ 207.51937984],
       [ 146.43455497],
       [  39.        ],
       [  33.03645833],
       [  81.94473684],
       [ 153.55844156],
       [  96.6953125 ],
       [ 204.9609375 ],
       [  65.86910995],
       [ 109.        ],
       [ 260.        ],
       [ 111.45953003],
       [ 207.43002545],
       [  72.64583333],
       [ 170.        ],
       [  90.21052632],
       [  35.        ],
       [  78.        ],
       [  53.        ],
       [  71.13740458],
       [ 272.8359375 ],
       [ 127.        ],
       [ 139.9562982 ],
       [ 114.16103896],
       [ 231.3125    ],
       [  52.89126214],
       [  40.97911227],
       [1200.        ],
       [  79.97668394],
       [  56.28871391],
       [ 250.05483029],
       [  47.92650919],
       [ 101.12631579],
       [  43.01578947],
       [ 152.56701031],
       [ 179.21336761],
       [  91.        ],
       [ 208.        ],
       [ 281.56657963],
       [ 158.5078534 ],
       [ 104.78947368],
       [  79.81038961],
       [ 175.        ],
       [  37.        ],
       [  90.36315789],
       [ 170.        ],
       [ 175.        ],
       [ 177.52645503],
       [ 160.        ],
       [ 118.74160207],
       [ 180.        ],
       [  94.74472169],
       [  40.        ],
       [ 234.14038462],
       [ 195.        ],
       [  62.17525773],
       [  62.        ],
       [1200.        ],
       [  43.14368932],
       [  68.54947917],
       [ 239.96303502],
       [1000.        ],
       [ 155.12073491],
       [ 409.54887218],
       [ 170.        ],
       [  73.07731959],
       [ 207.69487179],
       [  58.72386059],
       [ 700.        ],
       [  38.51171875],
       [ 124.7591623 ],
       [ 249.06493506],
       [  45.66666667],
       [  93.18393782],
       [ 230.72944297],
       [ 168.52331606],
       [ 195.        ],
       [ 104.70680628],
       [  90.264     ],
       [  72.39793282],
       [  54.66404199],
       [  79.07272727],
       [ 220.        ],
       [ 158.        ],
       [  41.11340206],
       [  47.        ],
       [  51.69350649],
       [  79.84126984],
       [  60.61757106],
       [  66.06788512],
       [ 683.94584139],
       [ 456.55769231],
       [  47.        ],
       [  86.13246753],
       [ 296.8814433 ],
       [ 137.89817232],
       [ 165.56842105],
       [  72.05384615],
       [  40.06753247],
       [ 113.58333333],
       [ 219.08349515],
       [ 270.63254593],
       [  42.10471204],
       [ 219.43603133],
       [  59.16020672],
       [  54.93175853],
       [  60.64893617],
       [ 180.        ],
       [  59.        ],
       [ 192.63020833],
       [ 240.        ],
       [ 177.4151436 ],
       [ 116.09947644],
       [ 355.52083333],
       [ 353.        ],
       [  73.25265957],
       [ 156.6171875 ],
       [  40.61578947],
       [  82.23643411],
       [  30.        ],
       [ 434.9132948 ],
       [  40.        ],
       [ 118.        ],
       [  65.675     ],
       [ 204.39276486],
       [  41.69712794],
       [  59.        ],
       [ 161.5503876 ],
       [ 474.14258189],
       [  57.        ],
       [ 409.        ],
       [  62.13533835],
       [ 130.        ],
       [ 168.91395793],
       [  79.        ],
       [ 307.01547389],
       [ 529.33418367],
       [  60.6873385 ],
       [ 135.85677083],
       [ 170.        ],
       [ 900.        ],
       [ 261.86046512],
       [ 160.        ],
       [  85.78608247],
       [  47.84031414],
       [  68.55844156],
       [ 350.88565891],
       [ 176.37075718],
       [  32.06266319],
       [ 108.49226804],
       [  17.9766537 ],
       [  17.86372361],
       [ 160.        ],
       [ 140.50895141],
       [ 871.3657289 ],
       [ 249.15028902],
       [  39.92307692],
       [ 850.65633075],
       [ 470.89267016],
       [ 158.84473684],
       [1157.74278215],
       [ 346.41343669],
       [  42.        ],
       [ 290.        ],
       [ 123.63829787],
       [ 102.38157895],
       [ 190.        ],
       [ 198.22680412],
       [ 108.56185567],
       [ 102.        ],
       [  40.        ],
       [ 230.01574803],
       [ 125.26109661],
       [ 306.13577023],
       [ 107.47409326],
       [ 146.57519789],
       [ 222.8042328 ],
       [ 186.17829457],
       [ 157.        ],
       [  30.        ],
       [  63.        ],
       [  42.        ],
       [  28.31937173],
       [ 600.        ],
       [ 129.17493473],
       [  89.        ],
       [  86.77922078],
       [ 126.30569948],
       [ 269.53846154],
       [  40.        ],
       [  51.01595745],
       [ 197.65815324],
       [ 196.58684211],
       [ 153.3203125 ],
       [ 119.34816754],
       [ 145.90322581],
       [  35.40932642],
       [ 525.        ],
       [ 300.        ],
       [  52.        ],
       [ 126.32198953],
       [ 505.61793372],
       [  71.01804124],
       [  70.43410853],
       [ 374.62273902],
       [ 139.17105263],
       [  40.10416667],
       [ 145.16966581],
       [ 170.        ],
       [ 450.        ],
       [ 400.        ],
       [  52.74293059],
       [  93.70234987],
       [ 195.        ],
       [ 137.        ],
       [ 263.125     ],
       [  96.        ],
       [ 192.57251908],
       [  52.        ],
       [  80.984375  ],
       [ 294.18181818],
       [ 158.91906005],
       [ 121.50259067],
       [ 117.        ],
       [ 690.99415205],
       [ 139.95844156],
       [ 150.61538462],
       [  59.        ],
       [  57.59689922],
       [ 350.        ],
       [  93.35248042],
       [ 165.        ],
       [ 304.84536082],
       [ 291.86387435],
       [  37.21818182],
       [ 109.421875  ],
       [ 152.67792208],
       [ 128.09043928],
       [  61.        ],
       [ 242.21052632],
       [ 114.95833333],
       [ 345.24806202],
       [  78.54736842],
       [ 226.49222798],
       [ 410.        ],
       [ 119.06349206],
       [  79.        ],
       [  57.88947368],
       [ 164.52196382],
       [  70.30989583],
       [ 122.30490956],
       [ 170.57989691],
       [  68.58461538],
       [ 202.27154047],
       [ 252.3126615 ],
       [ 153.63116883],
       [ 135.        ],
       [ 184.40789474],
       [  72.        ],
       [  59.57948718],
       [ 611.65803109],
       [ 156.19693095],
       [ 164.845953  ],
       [  88.        ],
       [ 169.77083333],
       [  78.        ],
       [ 226.60051546],
       [ 226.89210526],
       [ 144.54025974],
       [ 140.9132948 ],
       [ 210.35917313],
       [ 126.62239583],
       [  92.02337662],
       [  68.17708333],
       [  99.02597403],
       [ 992.72164948],
       [ 517.0984456 ],
       [1000.        ],
       [  85.40682415],
       [ 250.        ],
       [ 216.46421663],
       [ 199.90503876],
       [ 151.39790576],
       [ 250.19379845],
       [ 274.10485437],
       [  74.23320158],
       [ 197.38085938],
       [ 250.01298701],
       [ 161.33159269],
       [  60.05263158],
       [ 297.60309278],
       [  89.43307087],
       [  78.33595801],
       [  93.46475196],
       [  42.61658031],
       [ 190.        ],
       [ 111.86458333],
       [ 358.12121212],
       [  66.67560322],
       [ 148.76804124],
       [ 241.3003876 ],
       [ 330.46875   ],
       [ 177.        ],
       [ 146.98963731],
       [  49.96344648],
       [ 170.30548303],
       [ 596.9785575 ],
       [ 138.90721649],
       [ 399.47683398],
       [ 115.        ],
       [ 300.        ],
       [ 133.94270833],
       [ 134.20424403],
       [ 500.        ],
       [ 300.        ],
       [ 145.        ],
       [  78.01558442],
       [ 490.61662198],
       [  68.09549072],
       [ 190.        ],
       [  76.98153034],
       [ 156.24031008],
       [ 133.09230769],
       [ 131.        ],
       [ 160.        ],
       [ 195.        ],
       [ 182.21875   ],
       [ 106.71428571],
       [ 297.        ],
       [  82.5883905 ],
       [ 338.85934489],
       [ 220.        ],
       [ 690.        ],
       [ 298.36675462],
       [ 240.99197861],
       [ 120.32122371],
       [  35.        ],
       [ 145.70103093],
       [  83.34563107],
       [ 123.        ],
       [ 197.45914397],
       [ 670.        ],
       [  86.80687831],
       [  91.41798942],
       [ 154.97927461],
       [  55.34933333],
       [ 233.37452471],
       [ 211.66226913],
       [ 158.8       ],
       [  87.10416667],
       [ 317.72845953],
       [ 119.28759894],
       [ 323.48429319],
       [  94.67783505],
       [ 289.85796545],
       [ 122.58461538],
       [ 160.43766578],
       [  33.        ],
       [ 302.        ],
       [ 127.89405685],
       [ 140.38381201],
       [ 237.26041667],
       [  35.        ],
       [ 962.54025974],
       [ 111.81443299],
       [ 183.01151631],
       [ 256.84334204],
       [ 207.55363985],
       [  24.        ],
       [  65.48484848],
       [  39.14750958],
       [  35.45436893],
       [ 999.        ],
       [  26.        ],
       [ 163.08505155],
       [ 199.04483431],
       [  29.        ],
       [  52.16410256],
       [ 184.31168831],
       [ 135.11227154],
       [ 153.25      ],
       [ 989.76377953],
       [  40.06701031],
       [ 806.90909091],
       [  25.        ],
       [ 125.        ],
       [ 180.        ],
       [ 517.71235521],
       [  69.        ],
       [  59.53439153],
       [ 170.        ],
       [ 527.13867188],
       [ 186.02906977],
       [ 204.6342711 ],
       [ 240.32882012],
       [ 255.74904215],
       [ 250.72093023],
       [  65.74418605],
       [1300.        ],
       [ 119.        ],
       [ 108.95026178],
       [ 357.7046332 ],
       [ 102.31151832],
       [ 931.65535248],
       [  50.50642674],
       [ 180.        ],
       [ 176.86125654],
       [ 215.        ],
       [ 203.21025641],
       [ 210.02362205],
       [  41.        ],
       [  96.11168831],
       [  58.13020833],
       [ 197.68766404],
       [  73.78249337],
       [ 250.        ],
       [ 390.16184971],
       [  78.07915567],
       [ 170.        ],
       [ 421.97260274],
       [ 109.71611253],
       [ 209.62992126],
       [ 229.35384615],
       [ 500.30051813],
       [ 188.57253886],
       [ 210.        ],
       [ 133.61734694],
       [ 165.46858639],
       [ 181.24870466],
       [ 340.81007752],
       [ 617.13541667],
       [ 161.83116883],
       [ 450.        ],
       [  47.66925065],
       [  92.57631579],
       [ 219.5037594 ],
       [  71.46753247],
       [ 267.9843342 ],

In [87]:
X

     person_capacity  beds  bedrooms  bathrooms
0                  1     1         1        2.0
1                  2     1         1        1.0
2                  1     1         1        1.0
3                  3     2         2        1.0
4                  2     1         1        1.0
..               ...   ...       ...        ...
995                2     1         0        1.0
996                3     1         1        1.0
997                4     2         1        1.0
998                6     4         2        1.5
999                2     1         1        1.0

[1000 rows x 4 columns]

In [106]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30, random_state=42)
x_train

array([[4. , 2. , 1. , 1. ],
       [2. , 1. , 1. , 1. ],
       [6. , 4. , 3. , 1.5],
       ...,
       [4. , 2. , 2. , 1. ],
       [5. , 1. , 1. , 1. ],
       [2. , 1. , 1. , 1. ]])

In [107]:
x_train.shape

(699, 4)

In [108]:
x_test.shape

(300, 4)

In [109]:
y_train.shape

(699, 1)

In [110]:
y_test.shape

(300, 1)

In [115]:
linreg = linear_model.LinearRegression().fit(x_train, y_train)
linreg

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [122]:
linreg.coef_

array([[ 36.20879253, -26.20790472,  27.52192177,  95.59654916]])

In [124]:
linreg.intercept_

array([-46.69756447])

In [178]:
y_pred = linreg.predict(x_test)
y_pred

array([[ 134.22006884],
       [ 571.22728396],
       [ 122.63058679],
       [ 180.15517198],
       [  95.10866502],
       [ 339.48243544],
       [  96.42268207],
       [-306.69677656],
       [ 122.63058679],
       [ 546.60797348],
       [ 196.3621889 ],
       [  95.10866502],
       [ 329.48154763],
       [ 168.84026713],
       [ 170.42886137],
       [ 242.57186924],
       [ 196.3621889 ],
       [ 168.84026713],
       [ 329.48154763],
       [ 216.63854171],
       [ 122.63058679],
       [ 122.63058679],
       [ 392.7903923 ],
       [ 122.63058679],
       [ 122.63058679],
       [ 311.96051367],
       [ 168.84026713],
       [  95.10866502],
       [ 141.31834536],
       [ 122.63058679],
       [  95.10866502],
       [ 132.6314746 ],
       [ 141.31834536],
       [ 243.88588628],
       [  95.10866502],
       [ 168.84026713],
       [  96.42268207],
       [ 291.95873806],
       [ 285.75260895],
       [  95.10866502],
       [ 122.63058679],
       [ 122.63058679],
       [ 216.63854171],
       [ 387.28071002],
       [  95.10866502],
       [ 122.63058679],
       [ 122.63058679],
       [ 122.63058679],
       [ 158.83937932],
       [ 122.63058679],
       [ 216.63854171],
       [ 106.42356988],
       [ 206.36307671],
       [ 255.74994553],
       [ 195.04817185],
       [ 323.27541853],
       [ 158.83937932],
       [ 122.63058679],
       [ 466.52199441],
       [ 313.27453072],
       [ 242.57186924],
       [ 122.63058679],
       [ 424.8035196 ],
       [  58.89987249],
       [ 338.1684184 ],
       [ 242.57186924],
       [ 132.6314746 ],
       [ 122.63058679],
       [ 180.15517198],
       [ 196.3621889 ],
       [  96.42268207],
       [ 411.9000205 ],
       [ 291.95873806],
       [ 196.3621889 ],
       [ 122.63058679],
       [  37.03492544],
       [ 254.16135129],
       [ 122.63058679],
       [ 205.04905966],
       [ 144.22095665],
       [ 158.83937932],
       [ 365.69034016],
       [ 206.36307671],
       [ 533.42989719],
       [ 438.10792522],
       [ 170.15428418],
       [ 191.74465403],
       [ 122.63058679],
       [ 170.15428418],
       [ 318.16664278],
       [ 338.1684184 ],
       [ 206.36307671],
       [ 148.83849151],
       [  95.10866502],
       [ 122.63058679],
       [ 132.6314746 ],
       [ 291.95873806],
       [ 196.3621889 ],
       [ 132.6314746 ],
       [  95.10866502],
       [ 132.6314746 ],
       [ 168.84026713],
       [  95.10866502],
       [  95.10866502],
       [ 364.37632312],
       [  95.10866502],
       [  96.42268207],
       [ 122.63058679],
       [ 148.83849151],
       [ 122.63058679],
       [ 122.63058679],
       [ 168.84026713],
       [  86.42179426],
       [ 132.6314746 ],
       [  38.62351968],
       [ 168.84026713],
       [ 196.3621889 ],
       [  34.00598482],
       [ 291.95873806],
       [ 232.57098143],
       [ 572.541301  ],
       [  95.10866502],
       [ 122.63058679],
       [  86.42179426],
       [  95.10866502],
       [ 122.63058679],
       [  95.10866502],
       [ 274.4377041 ],
       [ 122.63058679],
       [  86.42179426],
       [  96.42268207],
       [ 257.4648691 ],
       [ 221.25607657],
       [ 195.04817185],
       [  95.10866502],
       [ 242.57186924],
       [  96.42268207],
       [ 450.73684712],
       [ 122.63058679],
       [ 196.3621889 ],
       [ 122.63058679],
       [ 291.95873806],
       [ 485.9061998 ],
       [ 453.21758878],
       [ 178.84115494],
       [  86.42179426],
       [ 509.0851639 ],
       [ 221.25607657],
       [ 217.95255876],
       [ 122.63058679],
       [ 242.57186924],
       [ 219.541153  ],
       [ 168.84026713],
       [ 132.6314746 ],
       [ 216.36396451],
       [ 678.41331517],
       [ 122.63058679],
       [ 141.31834536],
       [ 132.6314746 ],
       [  95.10866502],
       [ 242.57186924],
       [ 122.63058679],
       [ 132.6314746 ],
       [ 168.84026713],
       [ 143.94637945],
       [ 141.31834536],
       [  95.10866502],
       [ 242.57186924],
       [  95.10866502],
       [ 168.84026713],
       [  95.10866502],
       [ 196.3621889 ],
       [ 226.63942952],
       [  95.10866502],
       [ 144.22095665],
       [ 339.75701264],
       [ 365.69034016],
       [  58.89987249],
       [ 397.00702063],
       [ 497.74834052],
       [  68.9007603 ],
       [  11.10159791],
       [ 221.25607657],
       [ 122.63058679],
       [ 458.10970084],
       [ 122.63058679],
       [ 291.95873806],
       [ 168.84026713],
       [ 105.10955283],
       [ 304.98856649],
       [ 338.1684184 ],
       [ 122.63058679],
       [ 122.63058679],
       [ 482.87725918],
       [ 264.43681629],
       [ 158.83937932],
       [ 196.3621889 ],
       [ 338.1684184 ],
       [ 271.40780805],
       [ 122.63058679],
       [ 365.69034016],
       [ 122.63058679],
       [ 122.63058679],
       [ 158.83937932],
       [ 122.63058679],
       [ 365.69034016],
       [ 195.04817185],
       [  95.10866502],
       [ 168.84026713],
       [  95.10866502],
       [ 122.63058679],
       [ 338.1684184 ],
       [ 270.093791  ],
       [ 132.6314746 ],
       [ 158.83937932],
       [ 196.3621889 ],
       [ 122.63058679],
       [ 207.95167095],
       [ 122.63058679],
       [ 122.63058679],
       [ 291.95873806],
       [ 132.6314746 ],
       [ 122.63058679],
       [ 141.31834536],
       [  86.42179426],
       [ 232.57098143],
       [ 122.63058679],
       [ 141.31834536],
       [ 122.63058679],
       [ 195.04817185],
       [ 122.63058679],
       [ 152.63325022],
       [ 122.63058679],
       [ 122.63058679],
       [  95.10866502],
       [ 187.5280257 ],
       [ 168.84026713],
       [ 195.04817185],
       [ 471.28777713],
       [ 180.15517198],
       [ 122.63058679],
       [ 170.15428418],
       [ 122.63058679],
       [ 123.94460384],
       [ 195.04817185],
       [  86.42179426],
       [ 168.84026713],
       [  68.9007603 ],
       [ 122.63058679],
       [ 384.10352154],
       [ 105.10955283],
       [ 168.84026713],
       [  95.10866502],
       [ 122.63058679],
       [ 122.63058679],
       [ 144.22095665],
       [ 242.57186924],
       [ 328.16753059],
       [ 170.15428418],
       [ 122.63058679],
       [ 483.00358852],
       [ 365.69034016],
       [ 280.09467881],
       [  95.10866502],
       [ 307.34297881],
       [ 122.63058679],
       [ 196.3621889 ],
       [ 206.36307671],
       [  38.62351968],
       [ 170.15428418],
       [ 196.3621889 ],
       [ 196.3621889 ],
       [ 277.06573819],
       [  95.10866502],
       [ 122.63058679],
       [ 122.63058679],
       [ 132.6314746 ],
       [ 387.00613283],
       [ 168.84026713],
       [ 207.67709375],
       [ 206.36307671],
       [ 217.95255876],
       [  86.42179426],
       [  96.42268207],
       [ 168.84026713],
       [ 195.04817185],
       [ 122.63058679],
       [ 243.88588628],
       [ 122.63058679],
       [ 168.84026713],
       [ 404.37987435],
       [ 122.63058679],
       [ 122.63058679],
       [ 168.84026713],
       [ 158.83937932],
       [ 290.37014382],
       [  95.10866502],
       [ 158.83937932],
       [ 122.63058679],
       [  68.9007603 ]])

In [179]:
mean_squared_error(y_test, y_pred)

20361.84416948426

In [180]:
r2_score(y_test, y_pred)

0.41298243967788906